kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: api-emeawxai-qk3ze
  namespace: EMEAllm
  version: '1.0'
  tags: []
  domain: ai-platform
spec:
  api-spec:
    $path: ./api-spec-qk3ze.yml
  policy-sequence:
    - $ref: EMEAllm:freeflowpolicysequence-emeawxai-qk3ze:1.0
