kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: Authenticate-qk3ze
  namespace: EMEAllm
  version: '1.0'
  tags: []
  domain: ai-platform
  labels:
    gatewayTypes:
      - nano
spec:
  namespace: client
  operation:
    subscription: {}
