kind: LLMProvider
apiVersion: api.ibm.com/v1
metadata:
  name: emeawxai
  namespace: EMEAllm
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
  domain: ai-platform
spec:
  provider:
    type: watsonx
    operations:
      - InvokeWatsonxModels
      - InvokeWatsonxTextGen
      - InvokeWatsonxTokenize
    apiKeySecret: _nOgguLOsRBxO3yB1CySuRarEl_YzsO_e_2OeUNNgjIm
    tlsClientProfile: tls-client-profile-default:1.0.0
    inputMessage: request
    cachePolicy:
      cache:
        expire:
          static:
            seconds: 60
        scope:
          narrowScope: {}
        ignoreControlDirectives: true
    projectId: ee6929b2-5f18-41c6-94bb-738abe064414
    region: eu-de
    opVersion: "2024-03-14"
  product:
    $ref: EMEAllm:product-emeawxai-qk3ze:1.0
