kind: Quota
apiVersion: api.ibm.com/v1
metadata:
  name: watsonx-default-qk3ze
  namespace: EMEAllm
  version: '1.0'
  tags: []
  domain: ai-platform
  description: ''
spec:
  maxRequest: 1000
  interval: 1s
  extensions:
    dp-nano-gateway:
      apiVersion: api.ibm.com/v1
      spec:
        weightExpr: '1'
        exceedAction: continue
        intervalOffset: 0
        dynamicValue: ''
