openapi: 3.0.1
info:
  title: generateUser
  version: '1.0'
  contact:
    email: msit@ch.ibm.com
  description: this randomly creates a user with a lot of - supposedly - personal details
paths:
  /xml:
    summary: ''
    description: ''
    get:
      responses:
        '200':
          description: OK
      security:
        - clientID: []
  /sensitive:
    summary: ''
    description: ''
    get:
      responses:
        '200':
          description: OK
      security:
        - clientID: []
  /api:
    summary: ''
    description: ''
    get:
      responses:
        '200':
          description: OK
      security:
        - clientID: []
servers:
  - url: https://randomuser.me
components:
  securitySchemes:
    clientID:
      name: X-IBM-Client-Id
      in: header
      description: ''
      type: apiKey
