kind: Product
apiVersion: api.ibm.com/v1
metadata:
  name: randomuserProduct
  namespace: EMEAmsitExperimental
  version: '1.0'
  tags: []
spec:
  apis:
    - $ref: EMEAmsitExperimental:generateUser:1.0
  plans:
    - $ref: EMEAmsitExperimental:low-use:1.0
  extensions:
    portal-config:
      apiVersion: api.ibm.com/v1
      spec:
        visibility:
          view:
            type: public
            orgs: []
            enabled: true
            tags: []
          subscribe:
            type: authenticated
            orgs: []
            enabled: true
            tags: []
