kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: c1app2
  version: "1.0"
  namespace: EMEA-Testcases
  tags: []
spec:
  variables:
    - key: X-IBM-Client-Id
      isSecret: false
      value: 3537d94dda9f4ef728101b7992a44944
