kind: environment
apiVersion: api.ibm.com/v1
metadata:
  name: c1app1
  version: "1.0"
  namespace: EMEA-Testcases
  tags: []
spec:
  variables:
    - key: clientId
      isSecret: false
      value: 05ac74b27f27f943fca15fb2e987c352
