kind: assertion
apiVersion: api.ibm.com/v1
metadata:
  name: content-type
  namespace: EMEA-Testcases
  version: "1.0"
  tags: []
spec:
  - name: responsetime
    key: responseTime
    value: 200
    action: lessThan
