kind: assertion
apiVersion: api.ibm.com/v1
metadata:
  name: response code
  namespace: EMEA-Testcases
  version: '1.0'
  tags: []
spec:
  - name: status
    key: responseStatus
    value: 200
    action: equals
