kind: test
apiVersion: api.ibm.com/v1
metadata:
  name: test-branches
  namespace: EMEA-Testcases
  version: "1.0"
  tags: []
spec:
  api:
    $endpoint: https://rgw.apic-1ea39f2197613090e80c4981ab6eab96-0000.eu-de.containers.appdomain.cloud/apic/cms-idg-nano/sample-api.us-east-a.apiconnect.automation.ibm.com
  request:
    - method: GET
      resource: /bank/branches
      headers:
        - key: X-IBM-Client-Id
          value: ${c1app2}
      auth:
        noauth: true
      parameters: []
      assertions:
        - $ref: EMEA-Testcases:response code:1.0
        - $ref: EMEA-Testcases:content-type:1.0
      var: []
  environment:
    $ref: EMEA-Testcases:c2app1:1.0
