kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-randomuser-1
  namespace: EMEAnanoUsergen
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      verb: GET
      target:
        timeout: 30
        url: https://randomuser.me
