kind: Invoke
apiVersion: api.ibm.com/v1
metadata:
  name: invoke-randomuser1
  namespace: EMEAnanoUsergen
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  endpoint:
    http:
      target:
        timeout: 30
        url: https://randomuser.me/api
        tlsClientProfile: tls-client-profile-default:1.0.0
        urlType: plain
        version: HTTP/2
      verb: GET