kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: emeamcp-freeflowpolicysequence-blhnv
  namespace: EMEAmcp
  version: "1.0"
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: EMEAmcp:invoke-blhnv:1.0
  monitoring:
    $ref: EMEAmcp:telemetry-blhnv:1.0
